# Generated by Django 3.1.7 on 2021-12-24 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crew_network", "0002_auto_20211223_1657"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news_feed", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="hidden_from_crews",
            field=models.ManyToManyField(
                related_name="events_hidden", to="crew_network.Crew"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="hidden_from_friends",
            field=models.ManyToManyField(
                related_name="events_hidden", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="visible_to_crews",
            field=models.ManyToManyField(
                related_name="events_visible", to="crew_network.Crew"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="visible_to_friends",
            field=models.ManyToManyField(
                related_name="events_visible", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
