# Generated by Django 3.1.7 on 2021-12-24 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("skate_spots", "0004_spotalias"),
        ("news_feed", "0003_auto_20211224_1746"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="spot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="skate_spots.spot"
            ),
        ),
    ]
