# Generated by Django 3.1.7 on 2021-12-24 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_feed", "0004_auto_20211224_2130"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="privacy",
        ),
    ]
