# Generated by Django 3.1.7 on 2021-12-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_feed", "0006_auto_20211225_1147"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ("created_at", "user")},
        ),
        migrations.AlterModelOptions(
            name="eventresponse",
            options={"ordering": ("event", "user")},
        ),
    ]
