# Generated by Django 3.1.7 on 2021-12-25 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("news_feed", "0007_auto_20211225_1622"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="start_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
