# Generated by Django 3.1.7 on 2022-01-01 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crew_network", "0002_auto_20211223_1657"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news_feed", "0008_auto_20211225_1632"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="visible_to_crews",
            field=models.ManyToManyField(
                help_text="If supplied, it will be visible to *only* these friends/crews, not any and all friends",
                related_name="events_visible",
                to="crew_network.Crew",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="visible_to_friends",
            field=models.ManyToManyField(
                help_text="If supplied, it will be visible to *only* these friends/crews, not any and all friends",
                related_name="events_visible",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
