# Generated by Django 3.1.7 on 2022-01-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_feed", "0009_auto_20220101_2028"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="wheel_type",
            field=models.CharField(
                blank=True,
                choices=[("B", "B"), ("R", "R"), ("I", "I"), ("C", "C")],
                max_length=1,
                null=True,
            ),
        ),
    ]
