# Generated by Django 3.1.7 on 2021-12-23 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crew_network", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crew",
            name="owned_by",
            field=models.ForeignKey(
                help_text="User that made this crew, for their provacy reasons",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crews_owned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
