# Generated by Django 3.1.7 on 2021-12-23 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("skate_spots", "0003_spot_private"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotAlias",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skate_spots.spot",
                    ),
                ),
            ],
        ),
    ]
