# Generated by Django 3.1.7 on 2021-12-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skate_spots", "0004_spotalias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spot",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
