# Generated by Django 3.1.7 on 2021-12-25 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skate_spots", "0005_auto_20211225_1147"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spot",
            options={"ordering": ("name",)},
        ),
    ]
