# Generated by Django 3.1.7 on 2021-12-25 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ("username", "name")},
        ),
    ]
