# Generated by Django 4.0.1 on 2022-01-16 20:54

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20220116_1931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlocation",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
