# Generated by Django 4.0.1 on 2022-01-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_userlocation_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlocation",
            name="location",
        ),
        migrations.AlterField(
            model_name="userlocation",
            name="lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userlocation",
            name="lon",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
